server:
  port : 9092
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    port: 6379
    host: 39.108.239.32
    pool:
      max-active: 1024
      max-idle: 200
      max-wait: 10000
  kafka:
    producer:
      bootstrap-servers: 39.108.239.32:9092
    consumer:
      bootstrap-servers: 39.108.239.32:9092
      group-id: bbb
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

