server:
      port : 8082
spring:
      datasource:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://39.108.239.32:3306/ample16?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: admin
          type: com.alibaba.druid.pool.DruidDataSource
      freemarker:
            charset:UTF-8
            content-type:text/html
            charset:UTF-8
            expose-session-attributes:true
      resources:
            static-locations:classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:F:/upload
      redis:
            port: 6379
            host: 39.108.239.32
            pool:
              max-active: 1024
              max-idle: 200
              max-wait: 10000
      activemq:
            broker-url: tcp://39.108.239.32:61616
            user : admin
            password : admin
#mybatis:
#        mapperLocations: classpath:mapper/*.xml
#        typeAliasesPackage: com.example.demo.entity

